source "https://rubygems.org"

gem "rails", "~> 4"
gem "sqlite3", "1.3.10"
gem "sass-rails", "5.0.1"
gem "uglifier", "2.7.0"
gem "coffee-rails", "4.1.0"
gem "jquery-rails", "4.0.3"
gem "bootstrap-sass", "3.3.3"
gem "will_paginate", "3.0.7"
gem "prawn", "2.0.1" 
gem "prawn-table", "0.2.1"
group :test do
  gem "poltergeist", "1.6.0"
  gem "pry-rails", "0.3.4"
  gem "rspec-rails", "3.2.0"
  gem "factory_girl_rails", "4.5.0" 
  gem "capybara", "2.4.4"
  gem "capybara-webkit", "1.5.1"
  gem "database_cleaner", git: "git@github.com:bmabey/database_cleaner.git"
  gem "ruby_css_lint", "0.1.0"
end
